# 这是一个典型的 .rustfmt.toml 文件

# 每行的最大宽度
max_width = 100

# 控制缩进风格
hard_tabs = false
tab_spaces = 4

# 控制是否使用尾随逗号
trailing_comma = "Always"

# 控制操作符周围的空格使用
space_around_operators = true

# 控制函数参数周围的空格使用
fn_args_layout = "Compressed"

# 控制结构体字段周围的空格使用
struct_field_align_threshold = 20

# 控制 match 分支周围的空格使用
match_arm_blocks = true
